#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"


#set background
if [ -x "$(command -v feh)" ]; then
  #feh --bg-scale "${SCRIPTPATH}/background.png"
  feh --bg-scale "$(cat ~/.background)"
fi

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst -config ~/.config/dunst/dunstrc &
fi

# launch network-manager applet, but only if it's not already running
if [ -x "$(command -v nm-applet)"]; then
  ps aux | grep nm-applet | grep -v grep > /dev/null || nm-applet &
fi


#boot a polybar for each monitor
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do
  monitor=$monitor polybar -c config.ini main &> /tmp/polybar.log &
done

if [ -x "$(command -v blueberry-tray)"]; then
  ps aux | grep blueberry-tray | grep -v grep > /dev/null || blueberry-tray &
fi

# set up monitors
xrandr --output eDP-1 --mode 1920x1200

if xrandr | grep "HDMI-1 connected" > /dev/null; then
  xrandr --output HDMI-1 --mode 2560x1440 --right-of eDP-1
fi

WORKMODE=$(cat ~/.workmode)

# launch stuff for work, but only if it's not already running, and only if ~/.workmode == on
if [[ $WORKMODE == "on" ]]; then
  ps aux | grep "slack" | grep -v grep > /dev/null || slack &
  ps aux | grep "zoom" | grep -v grep > /dev/null || zoom &
  ps aux | grep "gpclient" | grep -v grep > /dev/null || gpclient &
fi
